### ISSUE TITLE
Improve Terminal-based UI

### ISSUE THREAD

**Issue by quiz3** [gursi26/music-player-rs#4]
The user interface in the terminal is very cool-looking but could use some improvements, including the following:
- Titles that get cut off should fill up their boxes if there is room
- The table of songs should allow for at least two-line space for song titles, as it cuts off many YouTube titles, which tend to often be very long in order to get tagged in a bunch of potential searches.
- The visualizer will be a nice addition when added.
- The currently playing song should either appear at the top of the queue in a different format from the others or just not at all, since it is displayed in its own section and is technically no longer in the queue anyway.

**Comment by gursi26** [comment]
Points 1 and 4 have been implemented. Point 2 will no longer be a problem with the addition of an `edit` subcommand, allowing users to change the name and artist of the song (or to directly download the song with a custom artist/song name). might return to this if it seems necessary later.
